# Generated by Django 6.1.1 on 2026-09-20 18:41

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_account(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    # Create Superuser / Admin Account
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@anchorcrest.com',
            password=make_password('AdminSecurePass123!'),
            is_staff=True,
            is_superuser=True,
            is_active=True
        )

def remove_admin_account(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_userprofile_address_alter_userprofile_role'),
    ]

    operations = [
        migrations.RunPython(create_admin_account, reverse_code=remove_admin_account),
    ]