# Generated by Django 6.1.1 on 2026-09-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_create_admin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ghana_card_image',
            field=models.ImageField(blank=True, help_text='Upload Ghana Card copy', null=True, upload_to='ghana_cards/'),
        ),
    ]
