# Generated by Django 6.1.1 on 2026-09-19 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='product',
        ),
        migrations.RenameField(
            model_name='amortizationschedule',
            old_name='interest_due',
            new_name='amount_due',
        ),
        migrations.RemoveField(
            model_name='amortizationschedule',
            name='principal_due',
        ),
        migrations.RemoveField(
            model_name='amortizationschedule',
            name='total_installment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='amortizationschedule',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='LoanProduct',
        ),
    ]
