# Generated by Django 6.1.1 on 2026-09-20 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='principal_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='term_months',
            new_name='duration_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='loan',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='applied_by_staff',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(help_text='Select a registered client', on_delete=django.db.models.deletion.CASCADE, related_name='client_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='AmortizationSchedule',
        ),
    ]
