# Generated by Django 6.1.1 on 2026-09-21 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_repayment_collected_by_alter_repayment_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='amount_requested',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='term_months',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
