# Generated by Django 6.1.1 on 2026-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loanapplication_amount_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='duration_months',
            field=models.IntegerField(default=3, help_text='Duration in Months (1 Month = 4 Weeks)'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Interest Rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Principal Amount (GHS)', max_digits=12),
        ),
    ]
